import unjs from 'eslint-config-unjs';

export default unjs({
    rules: {
        '@typescript-eslint/naming-convention': 'off',
        '@typescript-eslint/no-duplicate-enum-values': 'off',
        '@typescript-eslint/semi': 'off',
        'curly': ['error', 'all'],
        'eqeqeq': 'warn',
        'no-throw-literal': 'warn',
        'semi': 'off',
        '@typescript-eslint/indent': ['error', 4],
        'no-multiple-empty-lines': 'warn',
        'no-empty': 'warn',
        'unicorn/filename-case': 'off',
        'unicorn/prefer-event-target': 'off',
        'unicorn/no-null': 'off',
        'unicorn/no-array-for-each': 'off',
        'dot-notation': 'error',
        'no-lonely-if': 'error',
        'no-useless-rename': 'error',
        'object-shorthand': 'error',
        'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: false }],
        'require-await': 'error',
        'sort-imports': ['error', { ignoreDeclarationSort: true }],
        'no-unused-vars': 'off',
        '@typescript-eslint/no-unused-vars': 'off',
        'no-template-curly-in-string': 'off',
        'array-callback-return': 'off',
        'camelcase': 'off',
        'no-console': 'off',
        'quotes': ['error', 'single'],
        'comma-spacing': ['error', { before: false, after: true }],
        'keyword-spacing': ['error', { before: true, after: true }],
        'space-before-function-paren': ['error', 'always'],
        'object-curly-spacing': ['error', 'always'],
        'arrow-spacing': ['error', { before: true, after: true }],
        'key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
        'space-before-blocks': ['error', 'always'],
        'space-infix-ops': ['error', { int32Hint: false }],
        '@typescript-eslint/no-explicit-any': 'off',
        '@typescript-eslint/ban-types': 'off',
        '@typescript-eslint/ban-ts-comment': 'off',
        '@typescript-eslint/no-extraneous-class': 'off',
        'comma-dangle': 'off',
    },
    ignores: [
        'out',
        'node_modules',
        '*.js',
        'src/sideBar/build'
    ]
});
